const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');
const { execSync, spawnSync } = require('child_process');
const os = require('os');

const NETSCAPE_HEADER = `# Netscape HTTP Cookie File\n# This file was generated by cookie_exporter.cjs\n`;
const cookiesFilePath = process.argv[3] || 'cookies.txt';

// Prevent infinite retries
let installAttempted = false;

/**
 * Get the path to Chrome after installation
 */
function getChromePath() {
  const cacheDir = os.homedir() + '/.cache/puppeteer';
  // Check for Windows Chrome path
  const chromePath = path.join(cacheDir, 'chrome', 'win64-*', 'chrome-win64', 'chrome.exe');
  
  // Use glob pattern manually
  const baseDir = path.join(cacheDir, 'chrome');
  if (fs.existsSync(baseDir)) {
    const versions = fs.readdirSync(baseDir);
    for (const version of versions) {
      const fullPath = path.join(baseDir, version, 'chrome-win64', 'chrome.exe');
      if (fs.existsSync(fullPath)) {
        console.log(`[Chromium] Found Chrome at: ${fullPath}`);
        return fullPath;
      }
    }
  }
  
  return null;
}

/**
 * Installs Chrome using npx puppeteer command
 * This is the most reliable way to ensure Chromium is available
 */
async function ensureChromiumInstalled() {
  console.log('[Chromium] Installing Chrome via npx puppeteer...');
  console.log('[Chromium] This may take 2-5 minutes on first install.');
  
  try {
    const cacheDir = os.homedir() + '/.cache/puppeteer';
    process.env.PUPPETEER_CACHE_DIR = cacheDir;
    
    console.log(`[Chromium] Cache directory: ${cacheDir}`);
    console.log(`[Chromium] ⏳ Starting download... this may take a few minutes...`);
    
    // Use spawnSync for better control and to capture output
    const result = spawnSync('npx', ['puppeteer', 'browsers', 'install', 'chrome'], {
      stdio: 'inherit',
      shell: true,
      cwd: process.cwd()
    });
    
    if (result.error) {
      throw result.error;
    }
    
    // Verify Chrome was installed
    const chromePath = getChromePath();
    if (!chromePath) {
      throw new Error('Chrome installation completed but executable not found');
    }
    
    console.log(`[Chromium] ✅ Chrome successfully installed at: ${chromePath}`);
    return chromePath;
  } catch (err) {
    console.error(`[Chromium] ❌ Failed to install Chrome: ${err.message}`);
    return null;
  }
}

function toNetscapeCookies(cookies) {
  return (
    NETSCAPE_HEADER +
    cookies
      .map((cookie) => {
        const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
        const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expiry = cookie.expires || Math.floor(Date.now() / 1000) + 1209600; // 2 weeks
        return [
          domain,
          flag,
          cookie.path,
          secure,
          expiry,
          cookie.name,
          cookie.value,
        ].join('\t');
      })
      .join('\n')
  );
}

async function runExporter() {
  console.log("🚀 Launching Puppeteer to export cookies...");
  
  let chromePath = getChromePath();
  
  try {
    const launchOptions = {
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    };
    
    // Add Chrome path if found
    if (chromePath) {
      launchOptions.executablePath = chromePath;
    }
    
    const browser = await puppeteer.launch(launchOptions);

    try {
      const page = await browser.newPage();
      // Navigate to YouTube to ensure cookies are initialized/accessible
      await page.goto('https://www.youtube.com', { waitUntil: 'networkidle2', timeout: 30000 });

      const cookies = await page.cookies();
      const netscapeContent = toNetscapeCookies(cookies);

      fs.writeFileSync(cookiesFilePath, netscapeContent);
      console.log(`✅ Success: Cookies written to ${cookiesFilePath}`);
    } finally {
      await browser.close();
    }
  } catch (error) {
    const errorMsg = error.message || error.toString();
    
    // Check if it's a Chrome not found error and we haven't tried installing yet
    if ((errorMsg.includes('Could not find Chrome') || errorMsg.includes('Could not find Chromium')) && !installAttempted) {
      console.error(`❌ Chrome/Chromium not found!`);
      console.log(`[Chromium] Auto-installing Chromium...`);
      
      installAttempted = true; // Prevent infinite loop
      
      // Install Chromium and get path
      chromePath = await ensureChromiumInstalled();
      if (chromePath) {
        console.log('[Chromium] Retrying cookie export...');
        // Retry the function once
        await runExporter();
        return;
      } else {
        console.error(`❌ Failed to install Chromium. Please run manually:`);
        console.error(`   npx puppeteer browsers install chrome`);
      }
    } else {
      console.error(`❌ Error exporting cookies: ${errorMsg}`);
    }
  }
  
  process.exit(0);
}

runExporter();