const fs = require('fs');
const puppeteer = require('puppeteer');
const { computeSystemExecutablePath, BrowserFetcher } = require('@puppeteer/browsers');
const { execSync } = require('child_process');

const NETSCAPE_HEADER = `# Netscape HTTP Cookie File\n# This file was generated by cookie_exporter.cjs\n`;
const cookiesFilePath = process.argv[3] || 'cookies.txt';

/**
 * Installs Chrome using npx puppeteer command
 * This is the most reliable way to ensure Chromium is available
 */
async function ensureChromiumInstalled() {
  console.log('[Chromium] Installing Chrome via npx puppeteer...');
  console.log('[Chromium] This may take 2-5 minutes on first install.');
  
  try {
    const os = require('os');
    const cacheDir = os.homedir() + '/.cache/puppeteer';
    process.env.PUPPETEER_CACHE_DIR = cacheDir;
    
    console.log(`[Chromium] Cache directory: ${cacheDir}`);
    console.log(`[Chromium] ⏳ Starting download... this may take a few minutes...`);
    
    // Use the same npx command that setup scripts use
    execSync('npx puppeteer browsers install chrome', {
      stdio: 'inherit',
      shell: true
    });
    
    console.log(`[Chromium] ✅ Chrome successfully installed!`);
    return true;
  } catch (err) {
    console.error(`[Chromium] ❌ Failed to install Chrome: ${err.message}`);
    return false;
  }
}

function toNetscapeCookies(cookies) {
  return (
    NETSCAPE_HEADER +
    cookies
      .map((cookie) => {
        const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
        const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expiry = cookie.expires || Math.floor(Date.now() / 1000) + 1209600; // 2 weeks
        return [
          domain,
          flag,
          cookie.path,
          secure,
          expiry,
          cookie.name,
          cookie.value,
        ].join('\t');
      })
      .join('\n')
  );
}

async function runExporter() {
  console.log("🚀 Launching Puppeteer to export cookies...");
  
  try {
    const browser = await puppeteer.launch({ 
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'] 
    });

    try {
      const page = await browser.newPage();
      // Navigate to YouTube to ensure cookies are initialized/accessible
      await page.goto('https://www.youtube.com', { waitUntil: 'networkidle2' });

      const cookies = await page.cookies();
      const netscapeContent = toNetscapeCookies(cookies);

      fs.writeFileSync(cookiesFilePath, netscapeContent);
      console.log(`✅ Success: Cookies written to ${cookiesFilePath}`);
    } finally {
      await browser.close();
    }
  } catch (error) {
    const errorMsg = error.message || error.toString();
    
    // Check if it's a Chrome not found error
    if (errorMsg.includes('Could not find Chrome') || errorMsg.includes('Could not find Chromium')) {
      console.error(`❌ Chrome/Chromium not found!`);
      console.log(`[Chromium] Auto-installing Chromium in background...`);
      
      // Install Chromium and retry
      const installSuccess = await ensureChromiumInstalled();
      if (installSuccess) {
        console.log('[Chromium] Retrying cookie export...');
        // Retry the function recursively
        await runExporter();
        return;
      } else {
        console.error(`❌ Failed to install Chromium. Please run manually:`);
        console.error(`   npx puppeteer browsers install chrome`);
      }
    } else {
      console.error(`❌ Error exporting cookies: ${errorMsg}`);
    }
  }
  
  process.exit(0);
}

runExporter();